config/routes.rb
Rails.application.routes.draw do

  resources :settlement_rules do
    resources :settlement_prices
    member do
      put :refresh_products
      get :download
      get :upload
      post :upload
    end
  end

  resources :product_items
  resources :vouchers
  resources :user_card_charge_settings do
    collection do
      post :pay
      post :getList
    end
  end

  resources :order_promotions
  resources :user_promotions
  resources :category_promotions
  resources :promotion_rules
  resources :coupon_lists

  resources :coupons do
    collection do
      post :createCoupon
      post :getUsedCoupon
      post :getUnusedCoupon
      post :getInvalidCoupon
    end
  end
  resources :coupon_lists do
    collection do
      post :getList
    end
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :user_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :category_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :promotion_rules
  end

  resources :user_card_logs do
    collection do
      post :getList
    end
    end

  resources :user_cards do
    collection do
      post :getUserCard
    end
  end
  resources :items do
    collection do
      post :createItem
    end
  end

  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
      post :login
    end
  end
  resources :users  do
    resources :orders
    resources :user_cards do
      member do
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :couriers
  resources :factories do
    resources :factory_settlement_rules
    member do
      get :settlement_detail
    end
  end

  resources :roles

  resources :categories do 
    resources :products
    member do 
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules do
    collection do
      post :getPriceRules
    end
  end

  resources :stations do 
    collection do 
      get :suggestion
    end
  end

  resources :regions do 
    collection do 
      get :search
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
      post :createAddress
      post :getAddressByUser
    end
  end
  resources :cities

  resources :orders do
    resources :waybills
    member do 
      post :paidan
    end
    collection do
      post :sendOrder
      post :createOrder
      post :getOrderByUser
      post :pay
      post :getOrderByCourier
      post :getOrderByFactory
      post :sendToFactory
      post :createProductItem
      post :finishCleaning
    end
  end

  resources :waybills do
    collection do
      post :fightWaybill
    end
  end
end

app/models/coupon_list.rb
class CouponList < ApplicationRecord
  has_many :order_promotions
  has_many :user_promotions
  has_many :category_promotions
  has_many :promotion_rules

  def self.can_be_assigns
    today = Date.today
    CouponList.joins(:promotion_rules).where("promotion_rules.start_on <= ? and promotion_rules.end_on >= ?", today, today)
  end
end

app/controllers/coupon_lists_controller.rb
class CouponListsController < ApplicationController
  before_action :set_coupon_list, only: [:show, :edit, :update, :destroy]

  # GET /coupon_lists
  # GET /coupon_lists.json
  def index
    @coupon_lists = CouponList.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /coupon_lists/1
  # GET /coupon_lists/1.json
  def show
  end

  # GET /coupon_lists/new
  def new
    @coupon_list = CouponList.new
  end

  # GET /coupon_lists/1/edit
  def edit
  end

  # POST /coupon_lists
  # POST /coupon_lists.json
  def create
    @coupon_list = CouponList.new(coupon_list_params)

    respond_to do |format|
      if @coupon_list.save
        format.html { redirect_to @coupon_list, notice: 'Coupon list was successfully created.' }
        format.json { render :show, status: :created, location: @coupon_list }
      else
        format.html { render :new }
        format.json { render json: @coupon_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupon_lists/1
  # PATCH/PUT /coupon_lists/1.json
  def update
    respond_to do |format|
      if @coupon_list.update(coupon_list_params)
        format.html { redirect_to @coupon_list, notice: 'Coupon list was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon_list }
      else
        format.html { render :edit }
        format.json { render json: @coupon_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupon_lists/1
  # DELETE /coupon_lists/1.json
  def destroy
    @coupon_list.destroy
    respond_to do |format|
      format.html { redirect_to coupon_lists_url, notice: 'Coupon list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getList
    @OrderPromotion = OrderPromotion.find_by_sql(["SELECT * FROM order_promotions where coupon_list_id IN (SELECT id
FROM coupon_lists WHERE id IN (SELECT coupon_list_id FROM promotion_rules WHERE start_on <= NOW() AND end_on >= NOW()
 AND id IN (SELECT promotion_rule_id from cities_promotion_rules WHERE city_id = ?)) AND ((validity_type = 0 AND
valid_from <= NOW() AND valid_to >= NOW()) OR validity_type = 1))", params[:cityId]])
    @CategoryPromotion = CategoryPromotion.find_by_sql(["SELECT * FROM category_promotions where coupon_list_id IN
(SELECT id FROM coupon_lists WHERE id IN (SELECT coupon_list_id FROM promotion_rules WHERE start_on <= NOW() AND
end_on >= NOW() AND id IN (SELECT promotion_rule_id from cities_promotion_rules WHERE city_id = ?)) AND (
(validity_type = 0 AND valid_from <= NOW() AND valid_to >= NOW()) OR validity_type = 1))", params[:cityId]])
    respond_to do |format|
      format.json { render :json => {:orderPromotion => @OrderPromotion, :categoryPromotion => @CategoryPromotion}
                                        .to_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon_list
      @coupon_list = CouponList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_list_params
      params.require(:coupon_list).permit(:name, :validity_type, :valid_from, :valid_to, :fixed_begin_term, :fixed_term)
    end
end

app/helpers/coupon_lists_helper.rb
module CouponListsHelper
  def show_coupon_list_valid_type(validity_type)
    case validity_type
    when 0
      '绝对有效期'
    when 1
      '相对有效期'
    end
  end

  def show_coupon_list_valid(coupon_list)
    case coupon_list.validity_type
    when 0
      "从 #{coupon_list.valid_from} 到 #{coupon_list.valid_to}"
    when 1
      "领取后 #{coupon_list.fixed_begin_term} 天生效，有效期 #{coupon_list.fixed_term} 天"
    end
  end

  def show_coupon_list_promotion_type(coupon_list)
    case coupon_list.promotion_type
    when 'CategoryPromotion'
      '品类优惠'
    when 'OrderPromotion'
      '整单优惠'
    when 'CustomerPromotion'
      '用户等级优惠'
    end
  end
end

app/views/coupon_lists/_block.html.slim
table.table.table-striped.no-border
  tr
    td width='25%' 有效期类型
    td width='25%' = show_coupon_list_valid_type coupon_list.validity_type
    td width='25%' 优惠券有效期
    td width='25%' = show_coupon_list_valid coupon_list

app/views/coupon_lists/_coupon_list.html.slim
tr
  td = link_to coupon_list.name, coupon_list
  td = show_coupon_list_valid_type coupon_list.validity_type
  td = show_coupon_list_valid coupon_list
  td = link_to 'Edit', edit_coupon_list_path(coupon_list)
  td = link_to 'Destroy', coupon_list, data: { confirm: 'Are you sure?' }, method: :delete

app/views/coupon_lists/_form.html.slim
= simple_form_for(@coupon_list) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :validity_type, collection: [['绝对有效期', 0], ['相对有效期', 1]], include_blank: false
    = f.input :valid_from, as: :date_picker
    = f.input :valid_to, as: :date_picker
    = f.input :fixed_begin_term
    = f.input :fixed_term

  .form-actions
    = f.button :submit

javascript:
  $(function(){
    $("input.datepicker").each(function(input) {
      $(this).datepicker({
        dateFormat: "yy-mm-dd",
        altField: $(this).next()
      })
    })

    $('#coupon_list_validity_type').change(function(){
      reset_text()
    })
    reset_text()
  })

  function reset_text(){
    var kind = $('#coupon_list_validity_type').val();
    if(kind == 0){
      $('.coupon_list_valid_from').show();
      $('.coupon_list_valid_to').show();
      $('.coupon_list_fixed_begin_term').hide();
      $('.coupon_list_fixed_term').hide();
    }else{
      $('.coupon_list_valid_from').hide();
      $('.coupon_list_valid_to').hide();
      $('.coupon_list_fixed_begin_term').show();
      $('.coupon_list_fixed_term').show();
    }
  }

app/views/coupon_lists/edit.html.slim
h1 Editing coupon_list

== render 'form'

= link_to 'Show', @coupon_list
'|
= link_to 'Back', coupon_lists_path

app/views/coupon_lists/index.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading#places
        | 优惠券
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 名称
              th width='25%' 有效期类型
              th width='25%' 优惠券有效期
              th width='15%'
          tbody
            = render @coupon_lists
        = will_paginate @coupon_lists, renderer: BootstrapPagination::Rails
      .panel-footer
        = link_to '新建优惠券', new_coupon_list_path, class: 'btn btn-info btn-sm'

app/views/coupon_lists/new.html.slim
h1 New coupon_list

== render 'form'

= link_to 'Back', coupon_lists_path

app/views/coupon_lists/show.html.slim
ol.breadcrumb
  li.active
    = link_to '优惠券', coupon_lists_path
  li
    = @coupon_list.name

.clear
br

= render partial: 'block', locals: { coupon_list: @coupon_list}

.clear
br

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        | 整单优惠
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 类型
              th width='25%' 优惠内容
              th width='15%'
              th width='15%'
          tbody
            = render @coupon_list.order_promotions
      .panel-footer
        = link_to '新增', new_coupon_list_order_promotion_path(@coupon_list), class: 'btn btn-info btn-sm'

      .panel.panel-default
      .panel-heading
        | 品类优惠
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 类型
              th width='25%' 优惠内容
              th width='15%'
              th width='15%'
          tbody
            = render @coupon_list.category_promotions
      .panel-footer
        = link_to '新增', new_coupon_list_category_promotion_path(@coupon_list), class: 'btn btn-info btn-sm'

      .panel.panel-default
      .panel-heading
        | 用户优惠
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 类型
              th width='25%' 优惠内容
              th width='15%'
              th width='15%'
          tbody
            = render @coupon_list.user_promotions
      .panel-footer
        = link_to '新增', new_coupon_list_user_promotion_path(@coupon_list), class: 'btn btn-info btn-sm'

    .panel.panel-default
      .panel-heading
        | 优惠规则
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 城市
              th width='25%' 开始时间
              th width='25%' 结束时间
              th width='15%'
              th width='15%'
          tbody
            = render @coupon_list.promotion_rules
      .panel-footer
        = link_to '新增', new_coupon_list_promotion_rule_path(@coupon_list), class: 'btn btn-info btn-sm'