config/routes.rb
Rails.application.routes.draw do

  resources :settlement_rules do
    resources :settlement_prices
    member do
      put :refresh_products
      get :download
      get :upload
      post :upload
    end
  end

  resources :product_items
  resources :vouchers
  resources :user_card_charge_settings do
    collection do
      post :pay
      post :getList
    end
  end

  resources :order_promotions
  resources :user_promotions
  resources :category_promotions
  resources :promotion_rules
  resources :coupon_lists

  resources :coupons do
    collection do
      post :createCoupon
      post :getUsedCoupon
      post :getUnusedCoupon
      post :getInvalidCoupon
    end
  end
  resources :coupon_lists do
    collection do
      post :getList
    end
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :user_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :category_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :promotion_rules
  end

  resources :user_card_logs do
    collection do
      post :getList
    end
    end

  resources :user_cards do
    collection do
      post :getUserCard
    end
  end
  resources :items do
    collection do
      post :createItem
    end
  end

  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
      post :login
    end
  end
  resources :users  do
    resources :orders
    resources :user_cards do
      member do
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :couriers
  resources :factories do
    resources :factory_settlement_rules
    member do
      get :settlement_detail
    end
  end

  resources :roles

  resources :categories do 
    resources :products
    member do 
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules do
    collection do
      post :getPriceRules
    end
  end

  resources :stations do 
    collection do 
      get :suggestion
    end
  end

  resources :regions do 
    collection do 
      get :search
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
      post :createAddress
      post :getAddressByUser
    end
  end
  resources :cities

  resources :orders do
    resources :waybills
    member do 
      post :paidan
    end
    collection do
      post :sendOrder
      post :createOrder
      post :getOrderByUser
      post :pay
      post :getOrderByCourier
      post :getOrderByFactory
      post :sendToFactory
      post :createProductItem
      post :finishCleaning
    end
  end

  resources :waybills do
    collection do
      post :fightWaybill
    end
  end
end

app/models/settlement_rule.rb
class SettlementRule < ApplicationRecord
  belongs_to :category
  belongs_to :city

  has_many :settlement_prices
end

app/controllers/settlement_rules_controller.rb
class SettlementRulesController < ApplicationController
  before_action :set_settlement_rule, only: [:show, :edit, :update, :destroy, :refresh_products, :download, :upload]

  # GET /settlement_rules
  # GET /settlement_rules.json
  def index
    @settlement_rules = current_city.settlement_rules.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /settlement_rules/1
  # GET /settlement_rules/1.json
  def show
  end

  # GET /settlement_rules/new
  def new
    @settlement_rule = SettlementRule.new
  end

  # GET /settlement_rules/1/edit
  def edit
  end

  # POST /settlement_rules
  # POST /settlement_rules.json
  def create
    @settlement_rule = SettlementRule.new(settlement_rule_params.merge(city: current_city))

    respond_to do |format|
      if @settlement_rule.save
        format.html { redirect_to @settlement_rule, notice: 'Settlement rule was successfully created.' }
        format.json { render :show, status: :created, location: @settlement_rule }
      else
        format.html { render :new }
        format.json { render json: @settlement_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settlement_rules/1
  # PATCH/PUT /settlement_rules/1.json
  def update
    respond_to do |format|
      if @settlement_rule.update(settlement_rule_params)
        format.html { redirect_to @settlement_rule, notice: 'Settlement rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @settlement_rule }
      else
        format.html { render :edit }
        format.json { render json: @settlement_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settlement_rules/1
  # DELETE /settlement_rules/1.json
  def destroy
    @settlement_rule.destroy
    respond_to do |format|
      format.html { redirect_to settlement_rules_url, notice: 'Settlement rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def refresh_products
    @settlement_rule.category.products.each do |product|
      @settlement_rule.settlement_prices.create(product: product) if @settlement_rule.settlement_prices.where(product: product).empty?
    end
    redirect_to @settlement_rule
  end

  def download
    respond_to do |format|
      format.xlsx { response.headers['Content-Disposition'] = "attachment; filename='#{@settlement_rule.name}-加工商结算价格表.xlsx'"}
    end
  end

  def upload
    if request.post?
      p_l = Roo::Spreadsheet.open(params['settlement_rule']['file'].tempfile.path)
      
      sheet = p_l.sheet(0)
      l_c = p_l.last_column
      2.upto(p_l.last_row).each do |r|
        p_id = sheet.cell(r, 'A')
        p_name = sheet.cell(r, 'B')
        price = sheet.cell(r, 'C')

        settlement_price = @settlement_rule.settlement_prices.where(product_id: p_id).first
        
        if settlement_price
          settlement_price.update_attribute(:price, price)
        end
      end
      respond_to do |format|
        format.html { redirect_to @settlement_rule, notice: '结算价格更新成功！' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_settlement_rule
      @settlement_rule = SettlementRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def settlement_rule_params
      params.require(:settlement_rule).permit(:category_id, :city_id, :name, :comment)
    end
  end

app/views/settlement_rules/_form.html.slim
= simple_form_for(@settlement_rule) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :comment
    = f.association :category, collection: current_city.categories

  .form-actions
    = f.button :submit

app/views/settlement_rules/_settlement_rule.html.slim
tr
  td = settlement_rule.name
  td = settlement_rule.comment
  td = settlement_rule.category.name
  td = link_to 'Show', settlement_rule
  td = link_to 'Edit', edit_settlement_rule_path(settlement_rule)
  td = link_to 'Destroy', settlement_rule, data: { confirm: 'Are you sure?' }, method: :delete

app/views/settlement_rules/edit.html.slim
h1 Editing settlement_rule

== render 'form'

= link_to 'Show', @settlement_rule
'|
= link_to 'Back', settlement_rules_path

app/views/settlement_rules/index.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading#places
        | 结算价目表
      .panel-body
        table.table.table-striped
          thead
            tr
              th Name
              th Comment
              th Category
              th
              th
              th
          tbody
            = render @settlement_rules
        = will_paginate @settlement_rules, renderer: BootstrapPagination::Rails
      .panel-footer
        = link_to '新建结算规则', new_settlement_rule_path, class: 'btn btn-info btn-sm'

app/views/settlement_rules/new.html.slim
h1 New settlement_rule

== render 'form'

= link_to 'Back', settlement_rules_path

app/views/settlement_rules/show.html.slim
ol.breadcrumb
  li.active 
    = link_to '加工商结算价目表', settlement_rules_path
  li
    = @settlement_rule.name

.clear
br

table.table.table-striped.no-border
  tr
    td width='25%' 品类
    td width='25%' = @settlement_rule.category.name
    td width='25%' 备注
    td width='25%' = @settlement_rule.comment

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        | 价格表
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='25%' 商品
              th width='25%' 结算价格
          tbody
            = render @settlement_rule.settlement_prices
      .panel-footer
        = link_to '刷新商品列表', refresh_products_settlement_rule_path(@settlement_rule), class: 'btn btn-info btn-sm', method: :put
        |     
        = link_to '下载模板', download_settlement_rule_path(@settlement_rule, :format => :xlsx), class: 'btn btn-info btn-sm'
        |   
        = link_to '上传数据', upload_settlement_rule_path(@settlement_rule), class: 'btn btn-info btn-sm'

app/views/settlement_rules/upload.html.slim
= simple_form_for :settlement_rule, url: upload_settlement_rule_path(@settlement_rule) do |f|
  = f.error_notification

  .form-inputs
    = f.input :file, as: :file

  .form-actions
    = f.button :submit, '提交'