config/routes.rb
Rails.application.routes.draw do

  resources :settlement_rules do
    resources :settlement_prices
    member do
      put :refresh_products
      get :download
      get :upload
      post :upload
    end
  end

  resources :product_items
  resources :vouchers
  resources :user_card_charge_settings do
    collection do
      post :pay
      post :getList
    end
  end

  resources :order_promotions
  resources :user_promotions
  resources :category_promotions
  resources :promotion_rules
  resources :coupon_lists

  resources :coupons do
    collection do
      post :createCoupon
      post :getUsedCoupon
      post :getUnusedCoupon
      post :getInvalidCoupon
    end
  end
  resources :coupon_lists do
    collection do
      post :getList
    end
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :user_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :category_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :promotion_rules
  end

  resources :user_card_logs do
    collection do
      post :getList
    end
    end

  resources :user_cards do
    collection do
      post :getUserCard
    end
  end
  resources :items do
    collection do
      post :createItem
    end
  end

  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
      post :login
    end
  end
  resources :users  do
    resources :orders
    resources :user_cards do
      member do
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :couriers
  resources :factories do
    resources :factory_settlement_rules
    member do
      get :settlement_detail
    end
  end

  resources :roles

  resources :categories do 
    resources :products
    member do 
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules do
    collection do
      post :getPriceRules
    end
  end

  resources :stations do 
    collection do 
      get :suggestion
    end
  end

  resources :regions do 
    collection do 
      get :search
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
      post :createAddress
      post :getAddressByUser
    end
  end
  resources :cities

  resources :orders do
    resources :waybills
    member do 
      post :paidan
    end
    collection do
      post :sendOrder
      post :createOrder
      post :getOrderByUser
      post :pay
      post :getOrderByCourier
      post :getOrderByFactory
      post :sendToFactory
      post :createProductItem
      post :finishCleaning
    end
  end

  resources :waybills do
    collection do
      post :fightWaybill
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  has_many :prices, through: :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_category, only: [:show, :edit, :update, :destroy, :prices, :init_prices]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    params = category_params
    if params['logo']
      filename = generate_filename
      Image.upload(params['logo'].tempfile.path, filename)
      params['logo'] = filename
    end
    @category = Category.new(params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    params = category_params
    if params['logo']
      filename = generate_filename
      Image.upload(params['logo'].tempfile.path, filename)
      params['logo'] = filename
    end
    
    respond_to do |format|
      if @category.update(params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def prices
    @prices = @category.prices.paginate(page: params[:page], per_page: 10)
  end

  def init_prices
    @category.products.each do |product|
      product.create_price unless product.price
    end
    redirect_to prices_category_path(@category)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :logo, :is_del)
    end

    def generate_filename
      "category-#{Time.now.to_i * 1000 + rand(1000)}"
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :logo, as: :file

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to '详情', @category
'|
= link_to '返回', categories_path

app/views/categories/index.html.slim
.panel.panel-default
  .panel-heading
    | 品类
  .panel-body
    table.table.table-striped
      thead
        tr
          th 名称
          th 标志
          th 状态
          th
          th
          th

      tbody
        - @categories.each do |category|
          tr
            td = category.name
            td = image_tag qiniu_url(category.logo), size: '150x150'
            td
              - if category.is_del
                span.label.label-primary 是
              - else
                span.label.label-default 否 
            td = link_to '详情', category
            td = link_to '编辑', edit_category_path(category)
            td = link_to '删除', category, data: { confirm: '确认删除?' }, method: :delete

    = will_paginate @categories, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to '新建品类', new_category_path, class: 'btn btn-info btn-sm'

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to '返回', categories_path

app/views/categories/prices.html.slim
.panel.panel-default
  .panel-heading
    | 价格表
  .panel-body
    table.table.table-striped
      thead
        tr
          th 商品
          th width='10%' A
          th width='10%' B
          th width='10%' C
          th width='10%' D
          th width='10%' E
          th width='10%' F

      tbody
        - @prices.each do |price|
          tr
            td = price.product.name
            - 1.upto(6).each do |i|
              td 
                span.editable data={type: :text, name: "price[price#{i}]", 'url' => price_path(price)}
                  = price.send("price#{i}")
    = will_paginate @prices, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to '初始', init_prices_category_path(@category), class: 'btn btn-info btn-sm', method: :post

javascript:
  // 设置为空时的填充文字
  $('.editable').editable({
    emptytext: '-'
  });

  // 当弹出输入框时去掉输入框中的'-'
  $('.editable').on('shown', function(e, editable) {
    setTimeout(function() {
      $('.editable-input>input').focus();
      $('.editable-input>input').select();
    }, 0);
  });

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name
p
  strong Logo:
  = @category.logo
p
  strong Is del:
  = @category.is_del

= link_to '编辑', edit_category_path(@category)
'|
= link_to '返回', categories_path


.col-md-12
  .panel.panel-default
    .panel-heading#service_categories
      | 商品
    .panel-body
      table.table.table-striped
        thead
          tr
            th width='20%' 名称
            th width='15%' 标志
            th width='15%' 状态
            th width='5%' 
            th width='5%' 
        tbody
          = render @products
      = will_paginate @products, renderer: BootstrapPagination::Rails
    .panel-footer
      = link_to '新建商品', new_category_product_path(@category), class: 'btn btn-info btn-sm'