config/routes.rb
Rails.application.routes.draw do

  resources :settlement_rules do
    resources :settlement_prices
    member do
      put :refresh_products
      get :download
      get :upload
      post :upload
    end
  end

  resources :product_items
  resources :vouchers
  resources :user_card_charge_settings do
    collection do
      post :pay
      post :getList
    end
  end

  resources :order_promotions
  resources :user_promotions
  resources :category_promotions
  resources :promotion_rules
  resources :coupon_lists

  resources :coupons do
    collection do
      post :createCoupon
      post :getUsedCoupon
      post :getUnusedCoupon
      post :getInvalidCoupon
    end
  end
  resources :coupon_lists do
    collection do
      post :getList
    end
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :user_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :category_promotions, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :promotion_rules
  end

  resources :user_card_logs do
    collection do
      post :getList
    end
    end

  resources :user_cards do
    collection do
      post :getUserCard
    end
  end
  resources :items do
    collection do
      post :createItem
    end
  end

  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
      post :login
    end
  end
  resources :users  do
    resources :orders
    resources :user_cards do
      member do
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :couriers
  resources :factories do
    resources :factory_settlement_rules
    member do
      get :settlement_detail
    end
  end

  resources :roles

  resources :categories do 
    resources :products
    member do 
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules do
    collection do
      post :getPriceRules
    end
  end

  resources :stations do 
    collection do 
      get :suggestion
    end
  end

  resources :regions do 
    collection do 
      get :search
    end
  end

  resources :addresses do 
    collection do 
      get :suggestion
      post :createAddress
      post :getAddressByUser
    end
  end
  resources :cities

  resources :orders do
    resources :waybills
    member do 
      post :paidan
    end
    collection do
      post :sendOrder
      post :createOrder
      post :getOrderByUser
      post :pay
      post :getOrderByCourier
      post :getOrderByFactory
      post :sendToFactory
      post :createProductItem
      post :finishCleaning
    end
  end

  resources :waybills do
    collection do
      post :fightWaybill
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_one :price
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    respond_to do |format|
      if @product.save
        format.html { redirect_to @category, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    params = product_params
    if params['logo']
      filename = generate_filename
      Image.upload(params['logo'].tempfile.path, filename)
      params['logo'] = filename
    end
    respond_to do |format|
      if @product.update(params)
        format.html { redirect_to @category, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getByCityAndCategory
    @products = Product.select("products.id, products.name, products.logo, products.is_del, products.category_id,
prices.price1, prices.price2, prices.price3, prices.price4, prices.price5, prices.price6").joins("left join prices on
 prices.product_id = products.id").where (["category_id =?", params[:categoryId]])
    respond_to do |format|
      if @products.empty?
        format.json { render :json => {:data => "Get failed"}.to_json }
      else
        format.json { render :json => {:data => @products}.to_json }
      end
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :logo, :is_del, :category_id)
    end

    def generate_filename
      "category-#{Time.now.to_i * 1000 + rand(1000)}"
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= simple_form_for([@category, @product]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :logo, as: :file

  .form-actions
    = f.button :submit

app/views/products/_product.html.slim
tr
  td = product.name
  td = image_tag qiniu_url(product.logo), size: '150x150'
  td = product.is_del
  td = link_to 'Edit', edit_category_product_path(@category, product)
  td = link_to 'Destroy', category_product_path(@category, product), data: { confirm: 'Are you sure?' }, method: :delete

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Back', category_path(@category)

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th Name
      th Logo
      th Is del
      th Category
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = image_tag qiniu_url(product.logo), size: '150x150'
        td = product.is_del
        td = product.category
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', category_path(@category)

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Logo:
  = @product.logo
p
  strong Is del:
  = @product.is_del
p
  strong Category:
  = @product.category

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path